### ISSUE TITLE
Requesting Linux version

### ISSUE THREAD

**Issue by MostHated** [Ravbug/UnityHubNative#1]
Hey there,
    I was quite excited to come across this, as it looks great but then I saw there was no Linux version yet. : ( I will be keeping an eye on it for whenever it does come out!

Thanks,
-MH

**Comment by Ravbug** [comment]
Hello!

Linux support is planned, however I am unable to work on supporting it at the moment. I did however architect this application to make supporting Linux as easy as possible. 

Theoretically, all one would need to do is:
1. Define the missing platform-specific string constants in `globals.cpp` which tell the application where to find Unity's files on Linux (assuming this is standardized across distros)
2. Implement the Linux platform-specific call to launch the Unity process
3. Implement the Linux platform-specific call to view a file in the platform's file browser (which may not be trivial because there is no standard file browser on Linux)
4. Take out the compiler directive that stops you from compiling on Linux

As always, everything ends up being more complicated than it initially seems, however, if you, or anyone you know would like to attempt Linux support, I would be more than grateful. 
Setting up this repository for Linux is as easy as cloning the repo, `cd` into the root directory, and running `make` to compile (which will fail without the above aspects implemented)

Thank you for your interest in this application!

**Comment by Ravbug** [comment]
Hi, a Linux version is now available! A build is available in the [releases section](https://github.com/Ravbug/UnityHubNative/releases/latest), and compilation instructions are on the [readme](https://github.com/Ravbug/UnityHubNative/blob/master/README.md).
